# Generated by Django 5.0.2 on 2024-03-27 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devicer_admin', '0001_initial'),
        ('rooms', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/images')),
                ('category_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices_model', to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('processor', models.CharField(blank=True, max_length=70)),
                ('memory', models.CharField(blank=True, max_length=70)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('inventar_number', models.IntegerField(blank=True, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr-code')),
                ('category_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='device_category', to='main.category')),
                ('responsible_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devicer_admin.responsible')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
                ('model_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='main.model')),
            ],
        ),
    ]
