# Generated by Django 5.0.2 on 2024-03-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='inventar_number',
            new_name='inventory_number',
        ),
    ]
