# Generated by Django 5.0.2 on 2024-03-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_device_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
