# Generated by Django 5.0.2 on 2024-04-13 05:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_device_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='description',
        ),
        migrations.AddField(
            model_name='device',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='year',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
