# Generated by Django 5.0.2 on 2024-03-27 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('position', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('user', 'User')], max_length=10)),
                ('responsible_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devicer_admin.responsible')),
            ],
        ),
    ]
