# Generated by Django 5.0.2 on 2024-04-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicer_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsible',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
