# Generated by Django 5.0.2 on 2024-04-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicer_admin', '0002_responsible_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsible',
            name='department',
            field=models.TextField(null=True),
        ),
    ]
